services:
    minecraft-bedrock:
        image: itzg/minecraft-bedrock-server:latest
        ports:
            - 19132:19132/udp
        network_mode: host
        environment:
            - EULA=true
            - PACKAGE_BACKUP_KEEP=5

            # PERMISSIONS
            - OPS=2623078711549468

            # MINECRAFT SPECIFIC PROPERTIES
            - SERVER_NAME=minecraft-delight
            - LEVEL_NAME=minecraft-delight
            - LEVEL_SEED=8053335938660539988
            - GAMEMODE=survival
            - DIFFICULTY=hard
            - ALLOW_CHEATS=false
            - TICK_DISTANCE=6
            - PLAYER_IDLE_TIMEOUT=0
            - ALLOW_LIST=true
            - ALLOW_LIST_USERS=weagle07,f0xBaT,richaka6,drenab,The DeBator13,Vicious cbr,Mist3r Skull,Missus Sku1l,XavierOversized,MUSICPIZZAMAN
        stdin_open: true
        tty: true
        restart: unless-stopped
        volumes:
            - /minecraft-data:/data
